name: Deploy Pack DWUnmanagedSolution
 
on:
  workflow_run:
    workflows: ["Pack DWUnmanagedSolution"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pack-solution.yml
          name: packed-solution
      - uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: https://org6a4303aa.crm3.dynamics.com/
          app-id: ${{ secrets.APPLICATIONID }}
          client-secret: ${{ secrets.CLIENTSECRET }}
          tenant-id: ${{ secrets.TENANT }}
          solution-file: CONSO_DEMO_managed.zip
